### ISSUE TITLE
Suggestions and issues for "Discord RPC Client - NyanRPC"

### ISSUE THREAD

**Issue by Mittelblut9** [aiko-chan-ai/NyanRPC#1]
Hey👋! 
First of all, your rpc client is very nice to use and makes discord profiles even better!

## I have a few suggestion to make it maybe even better:

- maybe make the preview on the right as a live preview. Every time the user changed a value in the inputs it'll be changed (local)
- add more width to the inputs. They are kinda small.
- maybe add a tutorial how to get the application id as an external link under the input: **(https://support-dev.discord.com/hc/en-us/articles/360028717192-Where-can-I-find-my-Application-Team-Server-ID-)**

## Some issues:

- let the application install itself on the machine. It unpacks itself every time its starts
- the application kill the whole process when i press on "x". It would be better if it minimize it in the toolbar

ig this was all. 👍
I have one last question. Why don't you publish your code into public? People could help you easily. 🤔 But! Its your decision :)

I appreciate your work in this one! I hope these suggestions and issues are helpful.
👋

**Comment by aiko-chan-ai** [comment]
> Hey👋! First of all, your rpc client is very nice to use and makes discord profiles even better!
> 
> ## I have a few suggestion to make it maybe even better:
> * maybe make the preview on the right as a live preview. Every time the user changed a value in the inputs it'll be changed (local)
> * add more width to the inputs. They are kinda small.
> * maybe add a tutorial how to get the application id as an external link under the input: **(https://support-dev.discord.com/hc/en-us/articles/360028717192-Where-can-I-find-my-Application-Team-Server-ID-)**
> 
> ## Some issues:
> * let the application install itself on the machine. It unpacks itself every time its starts
> * the application kill the whole process when i press on "x". It would be better if it minimize it in the toolbar
> 
> ig this was all. 👍 I have one last question. Why don't you publish your code into public? People could help you easily. 🤔 But! Its your decision :)
> 
> I appreciate your work in this one! I hope these suggestions and issues are helpful. 👋

Thanks for your comments, I will consider it!
