### ISSUE TITLE
[FEAT] RPC Client - Translated to German

### ISSUE THREAD

**Issue by Mittelblut9** [aiko-chan-ai/NyanRPC#10]
# Hello everyone 👋

## Why have i opened this issue?
<strong>
As in every country, not everyone can speak or read english as perfect as the application needs.
I am a german dude and wants to help all others to understand what you guys wants to inform them in your application.
</strong>

## What have i done?
<strong>
I have translated every sentence i've found in the `en.json`file.
</strong>

<br />
<br />

The code:
https://pastebin.com/7UesGHXY

**Comment by aiko-chan-ai** [comment]
@Mittelblut9 Thank you very much for your interest in it, I will plan to open-source in a few days. You can create a PR, join us to contribute 👍

**Comment by aiko-chan-ai** [comment]
@Mittelblut9 open source here 🎉 https://github.com/hongduccodedao/Discord-RPC (`electron` branch)
