### ISSUE TITLE
Windows Defender Issue

### ISSUE THREAD

**Issue by Mittelblut9** [aiko-chan-ai/NyanRPC#2]
![image](https://user-images.githubusercontent.com/67608550/165578055-63a3bc25-6eb3-46a9-bc88-46bbc7978da6.png)

Hey 👋
When i try to download the setup exe my windows defender detect this file and remove it automatically.
I just saw it is at all previous versions. I installed the Nyan.exe only before and it workes perfectly.

Please fix if possible!

**Comment by aiko-chan-ai** [comment]
> ![image](https://user-images.githubusercontent.com/67608550/165578055-63a3bc25-6eb3-46a9-bc88-46bbc7978da6.png)
> 
> Hey 👋 When i try to download the setup exe my windows defender detect this file and remove it automatically. I just saw it is at all previous versions. I installed the Nyan.exe only before and it workes perfectly.
> 
> Please fix if possible!

I also don't know why it says that, but I guarantee it's virus free.
Maybe because before 1.3.0 I used express instead of ipcMain electron
I use windows defender win 11 and there is no virus notification

**Comment by aiko-chan-ai** [comment]
![image](https://user-images.githubusercontent.com/71698422/165734429-0734778d-36e9-4b16-a0dd-0d33bc50389c.png)
This is the test result using VirusTotal
https://www.virustotal.com/gui/file/1baffbdd6d32b25eece45e08cde11468dc5b55c53081e5ea089a3f025fb2d45b?nocache=1
