### ISSUE TITLE
Add a install script

### ISSUE THREAD

**Issue by CookieGMVN** [aiko-chan-ai/NyanRPC#3]
As #2 said, Windows Defender detected this is a virus/trojan. Can we create a python script or something else to download .exe file to a temp folder, disable Windows Defender for that folder and create a shortcut to Desktop?
P.S: I can help in creating that script :>

**Comment by aiko-chan-ai** [comment]
> As #2 said, Windows Defender detected this is a virus/trojan. Can we create a python script or something else to download .exe file to a temp folder, disable Windows Defender for that folder and create a shortcut to Desktop? P.S: I can help in creating that script :>

ok :))
