### ISSUE TITLE
Replit...?

### ISSUE THREAD

**Issue by Shkeffy** [aiko-chan-ai/NyanRPC#4]
Does this somehow work on Replit...? Or should I keep dreaming...[😔](https://emojipedia.org/pensive-face/)

**Comment by aiko-chan-ai** [comment]
> 

this is an exe application on windows :)?
but if you use ubuntu maybe i will develop on v2

**Comment by Shkeffy** [comment]
Idk how to use it on ubuntu, but thank you for answering.
