### ISSUE TITLE
Compiliting in mac.. ?

### ISSUE THREAD

**Issue by Leixy-Dev** [aiko-chan-ai/NyanRPC#5]
It will be very usefull to use this tool on macos, and electron can be compiling in macos without problems very easily. Why not ?

**Comment by Mittelblut9** [comment]
Sorry for my half-knowledge. Electron use zip files which macos can't read.

Maybe they can use Docker instead. I searched it up quick and found some people who said, using Docker is a solution to this problem. But i didnt looked closer into it 🤔

**Comment by aiko-chan-ai** [comment]
> Sorry for my half-knowledge. Electron use zip files which macos can't read.
> 
> Maybe they can use Docker instead. I searched it up quick and found some people who said, using Docker is a solution to this problem. But i didnt looked closer into it 🤔

the app development team doesn't use macos, so i can't help you :((
