### ISSUE TITLE
Token login

### ISSUE THREAD

**Issue by MaxMady** [aiko-chan-ai/NyanRPC#6]
Requesting for adding a token-login feature, for I dont wanna use the app for it to load. Both NyanRPC and Discord when opened crashes.

**Comment by aiko-chan-ai** [comment]
> Requesting for adding a token-login feature, for I dont wanna use the app for it to load. Both NyanRPC and Discord when opened crashes.

it's related to selfbot, so I recommend the selfbot repo
and rpc on selfbot can't use button
